#### ASTR 3890 - Selected Topics: Data Science for Large Astronomical Surveys (Spring 2022)
***N. Hernitschek***
___

# Homework 10
### Due: Monday, Apr 11th at 11.00am CST

The completed lecture notebook must also be submitted by 11:00am Central Time on Apr 11th.

---

## Problem 1

**Support Vector Machine**

scikit-learn has the benefit of using a common interface for most of its machine learning methods. This makes it easier to try out different methods without changing too much code.

Starting with what we saw in the `lecture_10.ipynb` notebook and the code snipplet below, use `sklearn.svm.SVC` to predict what type of iris has a 3cm x 5cm sepal and 4cm x 2cm petal. Don't forget the model validation.


### Solution

In [15]:
import numpy as np
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

iris = datasets.load_iris()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y)

Xmain_test = np.array([[3,5,4,2],])

model = SVC() # fill that in
model.fit(Xtrain,ytrain) # fill that in
result = model.predict(Xtest) # fill that in
print("validation")
print(confusion_matrix(ytest, result))

result_main = model.predict(Xmain_test)
print("3cm x 5cm sepal and 4cm x 2cm petal") 
print(iris.target_names[result_main]) # fill that in

validation
[[10  0  0]
 [ 0 16  1]
 [ 0  0 11]]
3cm x 5cm sepal and 4cm x 2cm petal
['versicolor']
