#### ASTR 3890 - Selected Topics: Data Science for Large Astronomical Surveys (Spring 2022)
***N. Hernitschek***
___

# Homework 10
### Due: Monday, Apr 11th at 11.00am CST

The completed lecture notebook must also be submitted by 11:00am Central Time on Apr 11th.

---

## Problem 1

**Support Vector Machine**

scikit-learn has the benefit of using a common interface for most of its machine learning methods. This makes it easier to try out different methods without changing too much code.

Starting with what we saw in the `lecture_10.ipynb` notebook and the code snipplet below, use `sklearn.svm.SVC` to predict what type of iris has a 3cm x 5cm sepal and 4cm x 2cm petal. Don't forget the model validation.


In [ ]:
from sklearn.svm import SVC
iris = datasets.load_iris()
X, y = iris.data, iris.target
Xtest = np.array([[3,5,4,2],])

model = ____() # fill that in
model.fit(____,____) # fill that in
result = ____.____(____) # fill that in
print(iris.target_names[result]) # fill that in

### Solution

In [33]:
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.model_selection import train_test_split

In [71]:
# Predict the type of iris given a 3cm x 5cm sepal and 4cm x 2cm petal
# No train-test split.
iris = datasets.load_iris()
X, y = iris.data, iris.target
Xtest = np.array([[3,5,4,2],])

model = SVC()
model.fit(X,y)
result = model.predict(Xtest)
print('Prediction:', iris.target_names[result])

Prediction: ['versicolor']
Model Score: 0.9733333333333334


In [92]:
# Model validation
# Confusion matrix for model above (no split)

print('Model Score:', model.score(X, y), '\n')

y_pred = model.predict(X)
print(confusion_matrix(y, y_pred))

Model Score: 0.9733333333333334 

[[50  0  0]
 [ 0 48  2]
 [ 0  2 48]]


There seems to be some confusion between the second and third iris species (versicolour and virginica).

In [144]:
# Repeat process with a train-test split.

Xtrain, Xtest_spl, ytrain, ytest = train_test_split(X, y, stratify=y)
model_spl = SVC()
model_spl.fit(Xtrain, ytrain)
result_spl = model_spl.predict(Xtest)
print('Prediction:', iris.target_names[result_spl])

Prediction: ['versicolor']


In [145]:
# Model validation
# Confusion matrix on test data for model above

print('Model Score on Test Data:', model_spl.score(Xtest_spl, ytest), '\n')

y_pred_spl = model_spl.predict(Xtest_spl)
print(confusion_matrix(ytest, y_pred_spl))

Model Score on Test Data: 0.9210526315789473 

[[13  0  0]
 [ 0 12  0]
 [ 0  3 10]]


Once again, there seems to be some confusion between the versicolour and virginica species.

It depends on how the data is split, but the model that has been trained on a split dataset may score better or worse than the model that was trained on the entire dataset.